"""Generates SPEC.md: which manual clause is enforced where, and by which test.

Read from the suite rather than maintained by hand, so the table cannot drift
away from what is actually pinned.

    python scripts/spec_matrix.py
"""

import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from emporio.spec import CLAUSES  # noqa: E402

HEADER = """# Traceability

The store policy manual is the specification for this agent. Each clause below is
declared in `src/emporio/spec.py`, enforced in the code named beside it, and
pinned by the tests in the last column.

This file is generated by `scripts/spec_matrix.py` from the `spec` markers in the
suite, and `tests/test_spec_coverage.py` fails if a declared clause loses its
test. Run `pytest -m spec` to execute only these.

| Clause | Requirement | Enforced in | Tests |
|---|---|---|---|
"""


def matrix() -> dict[str, set[str]]:
    """Maps clause section to the test functions marked with it."""
    import pytest

    found: dict[str, set[str]] = defaultdict(set)

    class Collector:
        def pytest_collection_modifyitems(self, items):
            for item in items:
                for mark in item.iter_markers(name="spec"):
                    for section in mark.args:
                        found[section].add(item.name.split("[")[0])

    pytest.main(["--collect-only", "-q", "--no-header", str(ROOT / "tests")],
                plugins=[Collector()])
    return found


def main() -> None:
    found = matrix()
    rows = []
    for clause in CLAUSES:
        tests = sorted(found.get(clause.section, []))
        rows.append(
            f"| §{clause.section} {clause.title} | {clause.requirement} | "
            f"`{clause.implemented_in}` | {', '.join(f'`{name}`' for name in tests) or '—'} |"
        )
    (ROOT / "SPEC.md").write_text(HEADER + "\n".join(rows) + "\n", encoding="utf-8")
    print(f"SPEC.md: {len(CLAUSES)} cláusulas, "
          f"{sum(len(v) for v in found.values())} testes rastreados")


if __name__ == "__main__":
    main()
